name: mlfd7
channels:
  - defaults
dependencies:
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - ca-certificates=2024.9.24
  - comm=0.2.1
  - contourpy=1.2.0
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - fonttools=4.51.0
  - freetype=2.12.1
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.4.0
  - ipykernel=6.29.5
  - ipython=8.15.0
  - jedi=0.19.1
  - joblib=1.4.2
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.0.15
  - packaging=24.1
  - pandas=2.2.2
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - platformdirs=3.10.0
  - prompt-toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybind11-abi=4
  - pygments=2.15.1
  - pyparsing=3.1.2
  - python=3.9.20
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - pyzmq=25.1.2
  - readline=8.2
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - seaborn=0.13.2
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - tzdata=2024b
  - unicodedata2=15.1.0
  - wcwidth=0.2.5
  - wheel=0.44.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.2.13
  - zstd=1.5.6
prefix: /opt/miniconda3/envs/mlfd6
